fn ServerConnect() {}
fn ServerDisconnect() {}
fn ServerSettings() {}
fn ServerStart() {}
fn ServerStop() {}
fn ServerRestart() {}
fn ServerStatus() {}
fn ServerPlayers() {}
fn ServerChat() {}
fn ServerLog() {}
fn ServerBan() {}
fn ServerKick() {}
fn ServerUnban() {}
fn ServerWhitelist() {}
fn ServerWhitelistAdd() {}
fn ServerWhitelistRemove() {}
fn ServerWhitelistList() {}
fn ServerWhitelistClear() {}
fn ServerWhitelistSave() {}
fn ServerWhitelistLoad() {}
fn ServerWhitelistImport() {}
fn ServerWhitelistExport() {}